version: '3.8'

services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl-job-admin
    ports:
      - "18080:8080" # 主机:容器
    environment:
      PARAMS: >
        --spring.datasource.url=jdbc:mysql://host.docker.internal:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        --spring.datasource.username=root
        --spring.datasource.password=yfz
        --xxl.job.login.username=admin
        --xxl.job.login.password=e10adc3949ba59abbe56e057f20f883e
        --xxl.job.accessToken=123456
    volumes:
      - ./xxl-job-log:/data/applogs
    restart: unless-stopped